<?php
/**
 * $Id: xoops_version.php v 1.0 8 May 2004 hsalazar Exp $
 * Module: Wordbook - a multicategory glossary
 * Version: v 1.16
 * Release Date: 8 May 2004
 * Author: hsalazar
 * Additions: Dario Garcia
 * Licence: GNU
 */
 
$glossdirname = basename( dirname( __FILE__ ) );

$modversion['name'] = _MI_WB_MD_NAME;
$modversion['version'] = "1.17";
$modversion['status'] = "RC-1";
$modversion['description'] = _MI_WB_MD_DESC;
$modversion['author'] = "McDonald";
$modversion['credits'] = "hsalazar, Catzwolf";
$modversion['support_site_url'] = "http://community.impresscms.org/modules/newbb/viewforum.php?forum=9";
$modversion['support_site_name'] = "ImpressCMS Community - Modules Support Forum";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/imglossary_logo.png";
$modversion['iconbig'] = "images/iglossary_iconsbig.png";
$modversion['iconsmall'] = "images/iglossary_iconsmall.png";
$modversion['dirname'] = $glossdirname;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/imglossary.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "wbcategories";
$modversion['tables'][1] = "wbentries";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "wb_search";

// Menu
global $xoopsUser, $xoopsDB, $xoopsModule;

$modversion['hasMain'] = 1;
$hModConfig =& xoops_gethandler('config');
$hModule =& xoops_gethandler('module');
if ($wordbookModule =& $hModule->getByDirname('wordbook'))
{
	$wordbookConfig =& $hModConfig->getConfigsByCat(0, $wordbookModule->getVar('mid'));
	//if ( isset($wordbookConfig['catsinmenu']) && $wordbookConfig['anonpost'] == 1 )
	if (($xoopsUser && ($wordbookConfig['allowsubmit'] == 1)) || ($wordbookConfig['anonpost'] == 1)) 
	{
	$modversion['sub'][1]['name'] = _MI_WB_SUB_SMNAME1;
	$modversion['sub'][1]['url'] = "submit.php";	
	}
}
//if ($xoopsUser)
//	{
//	$modversion['sub'][1]['name'] = _MI_WB_SUB_SMNAME1;
//	$modversion['sub'][1]['url'] = "submit.php";
//	}
$modversion['sub'][2]['name'] = _MI_WB_SUB_SMNAME2;
$modversion['sub'][2]['url'] = "request.php";
$modversion['sub'][3]['name'] = _MI_WB_SUB_SMNAME3;
$modversion['sub'][3]['url'] = "search.php";


$sql = $xoopsDB->query( "SELECT categoryID, name FROM " . $xoopsDB->prefix( "wbcategories" ) . " " );
$i = 3;
$hModConfig =& xoops_gethandler('config');
$hModule =& xoops_gethandler('module');
if ($wordbookModule =& $hModule->getByDirname('wordbook'))
{
	$wordbookConfig =& $hModConfig->getConfigsByCat(0, $wordbookModule->getVar('mid'));
	if ( isset($wordbookConfig['catsinmenu']) && $wordbookConfig['catsinmenu'] == 1 )
	{
	while ( list( $categoryID, $name ) = $xoopsDB->fetchRow( $sql ) )
		{
		$modversion['sub'][$i]['name'] = $name;
		$modversion['sub'][$i]['url'] = "category.php?categoryID=" . $categoryID . "";
		$i++;
		} 
	}
}

$modversion['blocks'][1]['file'] = "entries_new.php";
$modversion['blocks'][1]['name'] = _MI_WB_ENTRIESNEW;
$modversion['blocks'][1]['description'] = "Shows new entries";
$modversion['blocks'][1]['show_func'] = "b_entries_new_show";
$modversion['blocks'][1]['edit_func'] = "b_entries_new_edit";
$modversion['blocks'][1]['options'] = "datesub|5";
$modversion['blocks'][1]['template'] = "entries_new.html";

$modversion['blocks'][2]['file'] = "entries_top.php";
$modversion['blocks'][2]['name'] = _MI_WB_ENTRIESTOP;
$modversion['blocks'][2]['description'] = "Shows popular entries";
$modversion['blocks'][2]['show_func'] = "b_entries_top_show";
$modversion['blocks'][2]['edit_func'] = "b_entries_top_edit";
$modversion['blocks'][2]['options'] = "counter|5";
$modversion['blocks'][2]['template'] = "entries_top.html";

$modversion['blocks'][3]['file'] = "random_term.php";
$modversion['blocks'][3]['name'] = _MI_WB_RANDOMTERM;
$modversion['blocks'][3]['description'] = "Shows a random term";
$modversion['blocks'][3]['show_func'] = "b_entries_random_show";
$modversion['blocks'][3]['template'] = "entries_random.html";

// Templates
$modversion['templates'][1]['file'] = 'wb_category.html';
$modversion['templates'][1]['description'] = 'Display categories';
$modversion['templates'][2]['file'] = 'wb_index.html';
$modversion['templates'][2]['description'] = 'Display index';
$modversion['templates'][3]['file'] = 'wb_entry.html';
$modversion['templates'][3]['description'] = 'Display entry';
$modversion['templates'][4]['file'] = 'wb_letter.html';
$modversion['templates'][4]['description'] = 'Display letter';
$modversion['templates'][5]['file'] = 'wb_search.html';
$modversion['templates'][5]['description'] = 'Search in glossary';
$modversion['templates'][6]['file'] = 'wb_request.html';
$modversion['templates'][6]['description'] = 'Request a definition';
$modversion['templates'][7]['file'] = 'wb_submit.html';
$modversion['templates'][7]['description'] = 'Submit a definition';

// Config Settings (only for modules that need config settings generated automatically)
$modversion['config'][1]['name'] = 'allowsubmit';
$modversion['config'][1]['title'] = '_MI_WB_ALLOWSUBMIT';
$modversion['config'][1]['description'] = '_MI_WB_ALLOWSUBMITDSC';
$modversion['config'][1]['formtype'] = 'yesno';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 1;

$modversion['config'][2]['name'] = 'anonpost';
$modversion['config'][2]['title'] = '_MI_WB_ANONSUBMIT';
$modversion['config'][2]['description'] = '_MI_WB_ANONSUBMITDSC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 0;

$modversion['config'][3]['name'] = 'dateformat';
$modversion['config'][3]['title'] = '_MI_WB_DATEFORMAT';
$modversion['config'][3]['description'] = '_MI_WB_DATEFORMATDSC';
$modversion['config'][3]['formtype'] = 'textbox';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = 'd-M-Y H:i';

$modversion['config'][4]['name'] = 'perpage';
$modversion['config'][4]['title'] = '_MI_WB_PERPAGE';
$modversion['config'][4]['description'] = '_MI_WB_PERPAGEDSC';
$modversion['config'][4]['formtype'] = 'select';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 5;
$modversion['config'][4]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );

$modversion['config'][5]['name'] = 'indexperpage';
$modversion['config'][5]['title'] = '_MI_WB_PERPAGEINDEX';
$modversion['config'][5]['description'] = '_MI_WB_PERPAGEINDEXDSC';
$modversion['config'][5]['formtype'] = 'select';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 5;
$modversion['config'][5]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );

$modversion['config'][6]['name'] = 'autoapprove';
$modversion['config'][6]['title'] = '_MI_WB_AUTOAPPROVE';
$modversion['config'][6]['description'] = '_MI_WB_AUTOAPPROVEDSC';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 0;

$modversion['config'][7]['name'] = 'multicats';
$modversion['config'][7]['title'] = '_MI_WB_MULTICATS';
$modversion['config'][7]['description'] = '_MI_WB_MULTICATSDSC';
$modversion['config'][7]['formtype'] = 'yesno';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 1;

$modversion['config'][8]['name'] = 'catsinmenu';
$modversion['config'][8]['title'] = '_MI_WB_CATSINMENU';
$modversion['config'][8]['description'] = '_MI_WB_CATSINMENUDSC';
$modversion['config'][8]['formtype'] = 'yesno';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 0;

$modversion['config'][9]['name'] = 'catsperindex';
$modversion['config'][9]['title'] = '_MI_WB_CATSPERINDEX';
$modversion['config'][9]['description'] = '_MI_WB_CATSPERINDEXDSC';
$modversion['config'][9]['formtype'] = 'select';
$modversion['config'][9]['valuetype'] = 'int';
$modversion['config'][9]['default'] = 3;
$modversion['config'][9]['options'] = array( '1' => 1, '3' => 3, '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );

$modversion['config'][10]['name'] = 'adminhits';
$modversion['config'][10]['title'] = '_MI_WB_ALLOWADMINHITS';
$modversion['config'][10]['description'] = '_MI_WB_ALLOWADMINHITSDSC';
$modversion['config'][10]['formtype'] = 'yesno';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 0;

$modversion['config'][11]['name'] = 'mailtoadmin';
$modversion['config'][11]['title'] = '_MI_WB_MAILTOADMIN';
$modversion['config'][11]['description'] = '_MI_WB_MAILTOADMINDSC';
$modversion['config'][11]['formtype'] = 'yesno';
$modversion['config'][11]['valuetype'] = 'int';
$modversion['config'][11]['default'] = 1;

$modversion['config'][12]['name'] = 'rndlength';
$modversion['config'][12]['title'] = '_MI_WB_RANDOMLENGTH';
$modversion['config'][12]['description'] = '_MI_WB_RANDOMLENGTHDSC';
$modversion['config'][12]['formtype'] = 'textbox';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 150;

$modversion['config'][13]['name'] = 'linkterms';
$modversion['config'][13]['title'] = '_MI_WB_LINKTERMS';
$modversion['config'][13]['description'] = '_MI_WB_LINKTERMSDSC';
$modversion['config'][13]['formtype'] = 'yesno';
$modversion['config'][13]['valuetype'] = 'int';
$modversion['config'][13]['default'] = 1;

//Comments (Mondarse)
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'entryID';
$modversion['comments']['pageName'] = 'entry.php';

$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wordbook_com_approve';
$modversion['comments']['callback']['update'] = 'wordbook_com_update';
//Comments (Mondarse)

?>